# -*- coding: utf-8 -*-
"""ChatBot_langchain_openAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rd7rE9KTtdUVjTXRlQebjAhNdoh-e5a4

**Simple ChatBot using LangChain and OpenAi**
"""

#install packages
!pip install langchain -qU
!pip install langchain-openai -qU

#import libraries
import os
from google.colab import userdata

#initialize openAi LLM
from langchain_openai import ChatOpenAI

#set OpenAi key
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

#initialize the ChatOpenAi model
llm = ChatOpenAI(
    model = "gpt-3.5-turbo",
    temperature=0
)

#Initialize prompt template
from langchain_core.prompts import ChatPromptTemplate

#create a prompt template
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are an intelligent chatbot. Answer the following question"),
        ("user","{question}")
    ]
)

#Initialize output parser
from langchain_core.output_parsers import StrOutputParser
parser = StrOutputParser()

# Chain the promt,LLM  and output parser
chain = prompt | llm | parser

question = "What is Machine Learning?"
response = chain.invoke({"question":question})
print(response)

#Initialize prompt template for dynamic Intereaction

from langchain_core.prompts import MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage

#create a prompt template
prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessage(content="You are a intelligent chaybot. Answer the following question"),
        MessagesPlaceholder(variable_name="question")
    ]
)

#Chain the prompt, LLM and output parser
chain = prompt | llm | parser

question = "My name is sahaswari"
response = chain.invoke({"question":[HumanMessage(content=question)]})
print(response)

question = "Who am I?"
response = chain.invoke({"question":[HumanMessage(content=question)]})
print(response)

"""Add Chat History"""

#add chathistory also
prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessage(content="You are a intelligent chaybot. Answer the following question"),
        HumanMessage(content="My name is sahaswari"),
        AIMessage(content="Hi sahaswari! How can I help you today?"),
        MessagesPlaceholder(variable_name="question")
    ]
)

#chain the promt
chain = prompt | llm | parser

question = "Who am I?"
response = chain.invoke({"question":[HumanMessage(content=question)]})
print(response)

#add dinamic chat history also
prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessage(content="You are a intelligent chaybot. Answer the following question"),
        MessagesPlaceholder(variable_name="history"),
        MessagesPlaceholder(variable_name="question")
    ]
)

#Define chat history
history = [
    HumanMessage(content="My name is sahaswari"),
    AIMessage(content="Hi sahaswari! How can I help you today?"),
    HumanMessage(content="What is 2+5"),
    AIMessage(content="7")
]

#chain the prompt
chain = prompt | llm | parser

question = "Who am I?"
response = chain.invoke({"history":history, "question":[HumanMessage(content=question)]})
print(response)

"""Update history and display"""

history

#Extend the history
history.extend([HumanMessage(content=question),AIMessage(content=response)])

history

question = "What is my last question?"
response = chain.invoke({"history":history, "question":[HumanMessage(content=question)]})
print(response)

history

"""Limit the dispaly histoty"""

history[-4:]

question = "What is 7+5?"
response = chain.invoke({"history":history, "question":[HumanMessage(content=question)]})
print(response)

history

question = "What is WHo?"
response = chain.invoke({"history":history, "question":[HumanMessage(content=question)]})
print(response)

question = "What is my last question?"
response = chain.invoke({"history":history, "question":[HumanMessage(content=question)]})
print(response)

